# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
data modify entity @s CustomName set value ['',{text:aj.camera,color:'#00aced'},'.',{text:camera,color:light_purple},'.',{text:camera,color:gold}]
function animated_java:global/gu/get_entity_uuid_string
scoreboard players operation @s aj.id = aj.last_id aj.id