# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:ld rig_hash set value '3f245d8810b0b656e9bf7d5f9a9043569f664ccaa01a99b4f454b15cf4d2be9d'
scoreboard objectives add aj.enter.frame dummy
scoreboard objectives add aj.exit.frame dummy