# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:ld rig_hash set value '5545b2d94473e7e56ed9c619e4714bd214df5141c90caaeb78ed2f46072d6d71'
scoreboard objectives add aj.enter.frame dummy
scoreboard objectives add aj.exit.frame dummy