# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone2) {transformation: [-2.6667f,0f,0f,0.9063f,0f,2.6667f,0f,0f,0f,0f,-2.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-2.6667f,0f,0f,-0.9062f,0f,2.6667f,0f,0f,0f,0f,-2.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone5) {transformation: [-2.6667f,0f,0f,0f,0f,2.6667f,0f,0f,0f,0f,-2.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [-2.6667f,0f,0f,0f,0f,2.6667f,0f,0f,0f,0f,-2.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_water) {transformation: [-5.15f,0f,0f,2.4062f,0f,0.05f,0f,1.9438f,0f,0f,-5f,2.5313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:ld/animations/enter/zzz/frames/0_root_function