# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [15f,0f,0f,-3.5f,0f,15f,0f,0.4063f,0f,0f,15f,-28.45f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{"camera":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}},"locators":{}}