# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set #aj.check aj.i 1
$execute as $(uuid) at @s run return run $(command)
tellraw @a [{text:'',color:red},[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (aj:camera)'},'\n → '],'ᴇʀʀᴏʀ: ',{text:'Camera Not Found',underlined:true},'\n\n ','Camera ',{nbt:args.name,storage:'animated_java:temp',color:aqua},' does not exist!','\n Please ensure that its name is spelled correctly.','\n']