# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^0 ^0 ~0 ~0
data modify entity @s data.cameras.camera merge value { px: 0, py: 0, pz: 0, ry: 0, rx: 0 }