# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:camera/root/on_tick/transform_locators
function aj:camera/root/on_tick/select_camera_camera with storage animated_java:temp entry.data.cameras.camera