# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.camera.root] run return 0
execute if entity @s[tag=aj.camera.animation.wake_up.playing] run function animated_java:camera/animations/wake_up/zzz/on_tick
execute if entity @s[tag=aj.camera.animation.end_cutscene.playing] run function animated_java:camera/animations/end_cutscene/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:camera/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~