# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.camera.animation.wake_up.playing] run function aj:camera/animations/wake_up/zzz/on_tick
execute if entity @s[tag=aj.camera.animation.end_cutscene.playing] run function aj:camera/animations/end_cutscene/zzz/on_tick
function aj:camera/root/on_tick/transform_floating_entities
function aj:camera/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name