# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.os.animation.idle.playing] run function aj:os/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.os.animation.walk.playing] run function aj:os/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.os.animation.idle2.playing] run function aj:os/animations/idle2/zzz/on_tick
execute if entity @s[tag=aj.os.animation.hit.playing] run function aj:os/animations/hit/zzz/on_tick