# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp args
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.x double 1 run data get entity @s Pos[0] 1
execute store result storage animated_java:temp args.y double 1 run data get entity @s Pos[1] 1
execute store result storage animated_java:temp args.z double 1 run data get entity @s Pos[2] 1
data modify storage animated_java:temp args.blueprint_id set from storage animated_java:temp entry.data.blueprint_id
data modify storage animated_java:temp entry.data.rig_hash set value '560a1224805cbfcaaf32f6becef64c03d6df3438ef4fa7ed57391f9676e88a27'
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:global/root/outdated_warning/print with storage animated_java:temp args
execute on passengers run data merge entity @s {Glowing: 1b, glow_color_override: 16711680}
summon minecraft:text_display ~ ~ ~ { Tags:[ 'aj.global.entity', 'aj.outdated_rig_text_display', 'aj.new' ], text:[{text:'⚠ This rig instance is outdated! ⚠',color:red},'\\n It should be removed and re-summoned to ensure it functions correctly.'], alignment: 'center', billboard: 'vertical', shadow: true, transformation:{ translation:[0f,3f,0f], left_rotation:[0f,0f,0f,1f], right_rotation:[0f,0f,0f,1f], scale:[1f,1f,1f] } }
ride @n[ type=minecraft:text_display, tag=aj.outdated_rig_text_display, tag=aj.new, distance=..1 ] mount @s
tag @n[ type=minecraft:text_display, tag=aj.outdated_rig_text_display, tag=aj.new, distance=..1 ] remove aj.new