# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone1) {transformation: [-2.6667f,0f,0f,1.4375f,0f,2.6667f,0f,-2f,0f,0f,-2.6667f,3.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone2) {transformation: [-2.6667f,0f,0f,-1.5f,0f,2.6667f,0f,-2f,0f,0f,-2.6667f,3.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-2.6667f,0f,0f,0.5313f,0f,2.6667f,0f,-2f,0f,0f,-2.6667f,-2.9687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone5) {transformation: [-2.6667f,0f,0f,-0.5937f,0f,2.6667f,0f,-2f,0f,0f,-2.6667f,-2.9687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(water) {transformation: [-5.15f,0f,0f,2.4062f,0f,0.05f,0f,1.9438f,0f,0f,-5f,2.5313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:ld/animations/enter/zzz/frames/0_root_function