# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:camera"
data modify storage animated_java:temp entry.data.rig_hash set value "d9b2464495cb6e87c2bf3aa12c1ee1185f2949a2620c128e1c2a65beafa52bcc"
tp @s ~ ~ ~ ~ ~
summon minecraft:item_display ^0 ^0 ^0 {Tags:["","aj.camera.camera","aj.camera.camera.camera","aj.camera.entity","aj.camera.node","aj.camera.node.camera","aj.global.camera","aj.global.entity","aj.global.node","aj.global.node.camera","aj.global.root.child","aj.global.root.child.camera","aj.new"], teleport_duration: 2}
execute as @n[ type=minecraft:item_display, tag=aj.camera.camera.camera, tag=aj.new, distance=..3 ] run function aj:camera/zzz/summon/as_camera/camera
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.camera set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.cameras.camera.uuid set from storage animated_java:gu out
function aj:camera/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:camera/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:camera/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
function aj:camera/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
execute at @s run function aj:camera/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount