# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data merge value {"cameras":{"camera":{"px":0,"py":2,"pz":0,"ry":0,"rx":0}},"locators":{}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:camera/animations/wake_up/zzz/frames/146_root_function