# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.export_namespace set from entity @s data.export_namespace
data modify entity @s data.rig_hash set value 'a8b97139021c021c1113ae7e379e035d56d939b03147b8d289234a9293eacea7'