# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:camera/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '5a9fcc3ff21464ea577c845afbc9ecf03805c45fc5d45d34dd617865746d227b'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack