# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.ld.root] run return run tellraw @a [{text:'',color:red},[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (aj:ld)'},'\n → '],'ᴇʀʀᴏʀ: ',{text:'Function Not Executed as Root Entity',underlined:true},'\n\n ',{text:'[This Function]',color:yellow,hover_event:{action:show_text,value:[{color:yellow,text:'aj:ld/animations/exit/tween'}]}}," must be executed as the rig's root entity.",{text:'\n\n ≡ ',color:white,extra:[{text:'ꜱʜᴏᴡ ᴇxᴀᴍᴘʟᴇ ᴄᴏᴍᴍᴀɴᴅ',color:aqua,underlined:true,click_event:{action:suggest_command,command:'/execute as @e[tag=aj.ld.root] run function aj:ld/animations/exit/tween'}}]},['\n\n ',{italic:true,underlined:true,color:blue,text:'▶ Learn More ◀',click_event:{action:open_url,url:'https://animated-java.dev/docs/rigs/controlling-a-rig-instance'}}],'\n']
function aj:ld/animations/pause_all
tag @s add aj.ld.animation.exit.playing
$scoreboard players set @s aj.tween_duration $(duration)
$scoreboard players set @s aj.exit.frame $(to_frame)
scoreboard players operation #this aj.i = @s aj.tween_duration
tag @s add aj.transforms_only
execute at @s run function aj:ld/animations/exit/zzz/apply_frame {frame: 0}
$execute at @s run function aj:ld/animations/exit/zzz/apply_frame {frame: $(to_frame)}
tag @s remove aj.transforms_only
execute on passengers store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i