# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:camera/animations/pause_all
tag @s add aj.camera.animation.wake_up.playing
scoreboard players set @s aj.wake_up.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:camera/animations/wake_up/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only