# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.ld.animation.enter.playing] run function aj:ld/animations/enter/zzz/on_tick
execute if entity @s[tag=aj.ld.animation.exit.playing] run function aj:ld/animations/exit/zzz/on_tick
execute on passengers run rotate @s ~ ~