# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.camera.root] run return run tellraw @a [{text:'',color:red},[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (aj:camera)'},'\n → '],'ᴇʀʀᴏʀ: ',{text:'Function Not Executed as Root Entity',underlined:true},'\n\n ',{text:'[This Function]',color:yellow,hover_event:{action:show_text,value:[{color:yellow,text:'aj:camera/remove/this/without_on_remove_function'}]}}," must be executed as the rig's root entity.",{text:'\n\n ≡ ',color:white,extra:[{text:'ꜱʜᴏᴡ ᴇxᴀᴍᴘʟᴇ ᴄᴏᴍᴍᴀɴᴅ',color:aqua,underlined:true,click_event:{action:suggest_command,command:'/execute as @e[tag=aj.camera.root] run function aj:camera/remove/this/without_on_remove_function'}}]},['\n\n ',{italic:true,underlined:true,color:blue,text:'▶ Learn More ◀',click_event:{action:open_url,url:'https://animated-java.dev/docs/rigs/controlling-a-rig-instance'}}],'\n']
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp entry.data.cameras.camera
execute unless data storage animated_java:temp {entry:{data:{rig_hash: 'd9b2464495cb6e87c2bf3aa12c1ee1185f2949a2620c128e1c2a65beafa52bcc'}}} run function animated_java:global/remove/outdated_rig
function aj:camera/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack