# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:camera rig_hash set value '5a9fcc3ff21464ea577c845afbc9ecf03805c45fc5d45d34dd617865746d227b'
scoreboard objectives add aj.wake_up.frame dummy
scoreboard objectives add aj.end_cutscene.frame dummy