# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:camera/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.camera.node.item_display] run data merge entity @s { transformation: [-1f,0f,0f,-1.7812f,0f,1f,0f,1f,0f,0f,-1f,0.0187f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.camera.node.bone] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }