# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":0,"py":0.6571157949942129,"pz":0,"ry":28.648148148148152,"rx":33.440000000000005}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args