# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":0,"py":0.6896933096426504,"pz":0,"ry":7.523148148148152,"rx":51.562500000000014}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args