# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":0,"py":0.7881462151721867,"pz":0,"ry":357.7346511054492,"rx":54.01454754664257}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args