# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":0,"py":0.032243877965757256,"pz":0,"ry":0.15876644820403385,"rx":-85.96250571559229}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args