# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":0,"py":0.7286834716796875,"pz":0,"ry":354.77023319615915,"rx":3.9506172839506126}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args