# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:os rig_hash set value '560a1224805cbfcaaf32f6becef64c03d6df3438ef4fa7ed57391f9676e88a27'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle2.frame dummy
scoreboard objectives add aj.hit.frame dummy