# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:camera/animations/pause_all
scoreboard players set @s aj.end_cutscene.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:camera/animations/end_cutscene/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only