# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4688f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right_arm) { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,1.4375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left_arm) { transformation: [-1f,0f,0f,0.3438f,0f,1f,0f,1.4063f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body) { transformation: [-1.145f,0f,0f,0f,0f,1.145f,0f,0.8125f,0f,0f,-1.145f,-0.0312f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right_leg) { transformation: [-1f,0f,0f,-0.1562f,0f,1f,0f,0.625f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left_leg) { transformation: [-1f,0f,0f,0.1563f,0f,1f,0f,0.5938f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }