# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:camera rig_hash set value 'e82b65bb3efc4d5cbc1b4ad828be8b37911636bb3364cded6c0c9a1c0b7441c3'
scoreboard objectives add aj.wake_up.frame dummy
scoreboard objectives add aj.end_cutscene.frame dummy