# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:camera rig_hash set value 'd9b2464495cb6e87c2bf3aa12c1ee1185f2949a2620c128e1c2a65beafa52bcc'
scoreboard objectives add aj.wake_up.frame dummy