# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args set value {variant:'', animation:'', frame: 0}
$execute store success score #success aj.i run data modify storage animated_java:temp args set value $(args)
summon minecraft:item_display ~ ~ ~ { Tags:["","aj.camera.entity","aj.camera.root","aj.global.entity","aj.global.root","aj.new"], teleport_duration: 0, interpolation_duration: 1, Passengers:[], CustomName: ['',{text:aj.camera,color:'#00aced'},'.',{text:root,color:light_purple}], }
execute as @n[ type=minecraft:item_display, tag=aj.camera.root, tag=aj.new, distance=..0.01 ] run function aj:camera/zzz/summon/as_root_entity