# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone1) { transformation: [-2.6667f,0f,0f,0.5312f,0f,2.6667f,0f,-2f,0f,0f,-2.6667f,3.0313f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(bone2) { transformation: [-2.6667f,0f,0f,-0.5938f,0f,2.6667f,0f,-2f,0f,0f,-2.6667f,3.0313f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(bone4) { transformation: [-2.6667f,0f,0f,0.5313f,0f,2.6667f,0f,-2f,0f,0f,-2.6667f,-2.9687f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(bone5) { transformation: [-2.6667f,0f,0f,-0.5937f,0f,2.6667f,0f,-2f,0f,0f,-2.6667f,-2.9687f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(water) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }