# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.camera.root] run return run tellraw @a [{text:'',color:red},[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (aj:camera)'},'\n → '],'ᴇʀʀᴏʀ: ',{text:'Function Not Executed as Root Entity',underlined:true},'\n\n ',{text:'[This Function]',color:yellow,hover_event:{action:show_text,value:[{color:yellow,text:'aj:camera/animations/end_cutscene/tween'}]}}," must be executed as the rig's root entity.",{text:'\n\n ≡ ',color:white,extra:[{text:'ꜱʜᴏᴡ ᴇxᴀᴍᴘʟᴇ ᴄᴏᴍᴍᴀɴᴅ',color:aqua,underlined:true,click_event:{action:suggest_command,command:'/execute as @e[tag=aj.camera.root] run function aj:camera/animations/end_cutscene/tween'}}]},['\n\n ',{italic:true,underlined:true,color:blue,text:'▶ Learn More ◀',click_event:{action:open_url,url:'https://animated-java.dev/docs/rigs/controlling-a-rig-instance'}}],'\n']
function aj:camera/animations/pause_all
tag @s add aj.camera.animation.end_cutscene.playing
$scoreboard players set @s aj.tween_duration $(duration)
$scoreboard players set @s aj.end_cutscene.frame $(to_frame)
scoreboard players operation #this aj.i = @s aj.tween_duration
tag @s add aj.transforms_only
execute at @s run function aj:camera/animations/end_cutscene/zzz/apply_frame {frame: 0}
$execute at @s run function aj:camera/animations/end_cutscene/zzz/apply_frame {frame: $(to_frame)}
tag @s remove aj.transforms_only
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
function aj:camera/animations/end_cutscene/zzz/0 with storage animated_java:temp entry.data.uuids_by_name