# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
summon minecraft:item_display ^0 ^0 ^0 {Tags:["aj.camera.camera","aj.camera.camera.camera","aj.camera.entity","aj.camera.node","aj.camera.node.camera","aj.global.camera","aj.global.entity","aj.global.node","aj.global.node.camera","aj.global.root.child","aj.global.root.child.camera","aj.new"], teleport_duration: 2}
execute as @n[ type=minecraft:item_display, tag=aj.camera.camera.camera, tag=aj.new, distance=..2 ] run function animated_java:camera/zzz/summon/as_data_entity/as_camera/camera
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.camera_camera set from storage animated_java:gu out
data modify entity @s data.cameras.camera.uuid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.camera.node.item_display] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display set from storage animated_java:gu out